// This file imports from per-category modules
// to keep a clean, organized structure

export {
  FIRST_STEPS_BADGES,
  STREAK_BADGES,
  ACADEMIC_BADGES,
  EXCELLENCE_BADGES,
  PLAN_BADGES,
  COLLABORATION_BADGES,
  CHALLENGE_BADGES,
  IMPROVEMENT_BADGES,
  KNOWLEDGE_BADGES,
  MILESTONE_BADGES,
  GAMIFICATION_BADGES,
  RIGOR_BADGES,
  STRATEGY_BADGES,
} from './categories';
