import {
  FIRST_STEPS_BADGES,
  STREAK_BADGES,
  ACADEMIC_BADGES,
  EXCELLENCE_BADGES,
  PLAN_BADGES,
  COLLABORATION_BADGES,
  CHALLENGE_BADGES,
  IMPROVEMENT_BADGES,
  KNOWLEDGE_BADGES,
  MILESTONE_BADGES,
  GAMIFICATION_BADGES,
  RIGOR_BADGES,
  STRATEGY_BADGES,
} from './badgesByCategory';

import { BADGE_CATEGORIES_CONFIG } from './categoriesConfig';

export const LOGROS_DISPONIBLES = {
  ...FIRST_STEPS_BADGES,
  ...STREAK_BADGES,
  ...ACADEMIC_BADGES,
  ...EXCELLENCE_BADGES,
  ...PLAN_BADGES,
  ...COLLABORATION_BADGES,
  ...CHALLENGE_BADGES,
  ...IMPROVEMENT_BADGES,
  ...KNOWLEDGE_BADGES,
  ...MILESTONE_BADGES,
  ...GAMIFICATION_BADGES,
  ...RIGOR_BADGES,
  ...STRATEGY_BADGES,
};

export const BADGE_CATEGORIES = BADGE_CATEGORIES_CONFIG;

export default {
  LOGROS_DISPONIBLES,
  BADGE_CATEGORIES,
};
