/** First half of ICONS map. */
import type { ReactNode } from 'react';

import {
  arrowDownIcon,
  arrowLeftIcon,
  arrowRightIcon,
  arrowRightFromBracketIcon,
  arrowUpIcon,
  barsIcon,
  boltIcon,
  bookIcon,
  bookOpenIcon,
  calculatorIcon,
  cameraIcon,
  chartLineIcon,
  checkIcon,
  clockIcon,
  checkCircleIcon,
  chevronDownIcon,
  chevronLeftIcon,
  chevronRightIcon,
  chevronUpIcon,
  circleUserIcon,
  circleNotchIcon,
  clipboardIcon,
  clipboardListIcon,
  tasksIcon,
  cloudIcon,
} from './iconPaths/iconPaths1';
import {
  cogIcon,
  coinsIcon,
  copyIcon,
  crownIcon,
  ellipsisVerticalIcon,
  envelopeIcon,
  exclamationCircleIcon,
  exclamationTriangleIcon,
  eyeIcon,
  eyeSlashIcon,
  filterIcon,
  fireIcon,
  flaskIcon,
} from './iconPaths/iconPaths2';
import {
  gemIcon,
  globeIcon,
  graduationCapIcon,
  hardHatIcon,
  headsetIcon,
  heartIcon,
  homeIcon,
  hourglassIcon,
  infoCircleIcon,
  landmarkIcon,
  languageIcon,
  lightbulbIcon,
  lockIcon,
  medalIcon,
} from './iconPaths/iconPaths3';

export const ICONS_PART_A = {
  'arrow-down': arrowDownIcon,
  'arrow-left': arrowLeftIcon,
  'arrow-right': arrowRightIcon,
  'arrow-right-from-bracket': arrowRightFromBracketIcon,
  'arrow-up': arrowUpIcon,
  bars: barsIcon,
  bolt: boltIcon,
  book: bookIcon,
  'book-open': bookOpenIcon,
  calculator: calculatorIcon,
  camera: cameraIcon,
  'chart-line': chartLineIcon,
  check: checkIcon,
  clock: clockIcon,
  'check-circle': checkCircleIcon,
  'chevron-down': chevronDownIcon,
  'chevron-left': chevronLeftIcon,
  'chevron-right': chevronRightIcon,
  'chevron-up': chevronUpIcon,
  'circle-user': circleUserIcon,
  'circle-notch': circleNotchIcon,
  clipboard: clipboardIcon,
  'clipboard-list': clipboardListIcon,
  tasks: tasksIcon,
  cloud: cloudIcon,
  cog: cogIcon,
  coins: coinsIcon,
  copy: copyIcon,
  crown: crownIcon,
  'ellipsis-vertical': ellipsisVerticalIcon,
  envelope: envelopeIcon,
  'exclamation-circle': exclamationCircleIcon,
  'exclamation-triangle': exclamationTriangleIcon,
  eye: eyeIcon,
  'eye-slash': eyeSlashIcon,
  filter: filterIcon,
  fire: fireIcon,
  flask: flaskIcon,
  gem: gemIcon,
  globe: globeIcon,
  'graduation-cap': graduationCapIcon,
  'hard-hat': hardHatIcon,
  headset: headsetIcon,
  heart: heartIcon,
  home: homeIcon,
  hourglass: hourglassIcon,
  'info-circle': infoCircleIcon,
  landmark: landmarkIcon,
  language: languageIcon,
  lightbulb: lightbulbIcon,
  lock: lockIcon,
  medal: medalIcon,
} satisfies Record<string, ReactNode>;
