/** Second half of ICONS map. */
import type { ReactNode } from 'react';

import { messageIcon, microchipIcon, paperPlaneIcon } from './iconPaths/iconPaths3';
import {
  playIcon,
  playCircleIcon,
  questionIcon,
  quoteLeftIcon,
  rocketIcon,
  rulerIcon,
  shieldAltIcon,
  shoppingBagIcon,
  shoppingCartIcon,
  signInAltIcon,
  signOutIcon,
  spinnerIcon,
  squareRootVariableIcon,
  starIcon,
  sunIcon,
  moonIcon,
  timesIcon,
  trashIcon,
} from './iconPaths/iconPaths4';
import {
  trophyIcon,
  userIcon,
  userSlashIcon,
  warningIcon,
  xMarkIcon,
  bugIcon,
  robotIcon,
  creditCardIcon,
  mapIcon,
  zapIcon,
  awardIcon,
  bullseyeIcon,
  googleIcon,
  bitcoinIcon,
  paypalIcon,
} from './iconPaths/iconPaths5';
import {
  ccVisaIcon,
  ccMastercardIcon,
  ccAmexIcon,
  magicIcon,
  barChartIcon,
  thLargeIcon,
  usersIcon,
  flagIcon,
  brainIcon,
} from './iconPaths/iconPaths6';
import {
  ringIcon,
  calendarAltIcon,
  giftIcon,
  shareNodesIcon,
  editIcon,
  balanceScaleIcon,
  minusIcon,
  devicePhoneMobileIcon,
  dropletIcon,
  handshakeIcon,
} from './iconPaths/iconPaths7';

export const ICONS_PART_B = {
  message: messageIcon,
  microchip: microchipIcon,
  'paper-plane': paperPlaneIcon,
  play: playIcon,
  'play-circle': playCircleIcon,
  question: questionIcon,
  'quote-left': quoteLeftIcon,
  rocket: rocketIcon,
  ruler: rulerIcon,
  'shield-alt': shieldAltIcon,
  'shopping-bag': shoppingBagIcon,
  'shopping-cart': shoppingCartIcon,
  'sign-in-alt': signInAltIcon,
  'sign-out': signOutIcon,
  spinner: spinnerIcon,
  'square-root-variable': squareRootVariableIcon,
  star: starIcon,
  sun: sunIcon,
  moon: moonIcon,
  times: timesIcon,
  trash: trashIcon,
  trophy: trophyIcon,
  user: userIcon,
  'user-slash': userSlashIcon,
  warning: warningIcon,
  'x-mark': xMarkIcon,
  bug: bugIcon,
  robot: robotIcon,
  'credit-card': creditCardIcon,
  map: mapIcon,
  zap: zapIcon,
  award: awardIcon,
  bullseye: bullseyeIcon,
  google: googleIcon,
  bitcoin: bitcoinIcon,
  paypal: paypalIcon,
  'cc-visa': ccVisaIcon,
  'cc-mastercard': ccMastercardIcon,
  'cc-amex': ccAmexIcon,
  magic: magicIcon,
  'bar-chart': barChartIcon,
  'th-large': thLargeIcon,
  users: usersIcon,
  flag: flagIcon,
  brain: brainIcon,
  ring: ringIcon,
  'calendar-alt': calendarAltIcon,
  gift: giftIcon,
  'share-nodes': shareNodesIcon,
  edit: editIcon,
  'balance-scale': balanceScaleIcon,
  minus: minusIcon,
  'device-phone-mobile': devicePhoneMobileIcon,
  droplet: dropletIcon,
  handshake: handshakeIcon,
} satisfies Record<string, ReactNode>;
