export const ACHIEVEMENTS_LECTURA = [
  {
    id: 'read_importancia',
    category: 'lectura',
    title: 'Importancia leída',
    description: 'Marca como leída la sección Importancia en Lectura',
    icon: 'info-circle',
    target: 1,
    xpReward: 50,
    coinsReward: 25,
  },
  {
    id: 'read_informacion',
    category: 'lectura',
    title: 'Información leída',
    description: 'Marca como leída la sección Información en Lectura',
    icon: 'clipboard-list',
    target: 1,
    xpReward: 50,
    coinsReward: 25,
  },
  {
    id: 'read_consejos',
    category: 'lectura',
    title: 'Consejos leídos',
    description: 'Marca como leída la sección Consejos en Lectura',
    icon: 'lightbulb',
    target: 1,
    xpReward: 50,
    coinsReward: 25,
  },
] as const;
