export const STREAK_ACHIEVEMENT_IDS = ['const_1', 'const_30', 'const_180', 'const_365'] as const;

export const ACHIEVEMENTS_CONSTANCY_METAS = [
  {
    id: 'const_1',
    category: 'constancia',
    group: 'constancia_racha',
    title: 'Racha de Fuego',
    description: 'Alcanza una racha de 7 días seguidos estudiando',
    icon: 'fire',
    target: 7,
    xpReward: 200,
    coinsReward: 100,
  },
  {
    id: 'const_30',
    category: 'constancia',
    group: 'constancia_racha',
    title: 'Racha Imparable',
    description: 'Alcanza una racha de 30 días seguidos estudiando',
    icon: 'fire',
    target: 30,
    xpReward: 450,
    coinsReward: 225,
  },
  {
    id: 'const_180',
    category: 'constancia',
    group: 'constancia_racha',
    title: 'Semestre Constante',
    description: 'Alcanza una racha de 6 meses (180 días) seguidos estudiando',
    icon: 'medal',
    target: 180,
    xpReward: 900,
    coinsReward: 450,
  },
  {
    id: 'const_365',
    category: 'constancia',
    group: 'constancia_racha',
    title: 'Año Legendario',
    description: 'Alcanza una racha de 1 año (365 días) seguidos estudiando',
    icon: 'crown',
    target: 365,
    xpReward: 1500,
    coinsReward: 750,
  },
  {
    id: 'meta_1',
    category: 'metas',
    group: 'metas_nivel',
    title: 'Maestro del ICFES',
    description: 'Alcanza el nivel 5',
    icon: 'trophy',
    target: 5,
    xpReward: 1000,
    coinsReward: 500,
  },
  {
    id: 'time_1',
    category: 'constancia',
    group: 'constancia_tiempo',
    title: 'Maratón de Estudio',
    description: 'Estudia durante 2 horas seguidas',
    icon: 'clock',
    target: 120,
    xpReward: 150,
    coinsReward: 75,
  },
] as const;
