export const ACHIEVEMENTS_STUDY_PERFORMANCE = [
  {
    id: 'study_1',
    category: 'estudio',
    title: 'Primeros Pasos',
    description: 'Completa tus primeras 5 lecciones',
    icon: 'book',
    target: 5,
    xpReward: 100,
    coinsReward: 50,
  },
  {
    id: 'study_2',
    category: 'estudio',
    title: 'Estudiante Dedicado',
    description: 'Completa 20 lecciones',
    icon: 'graduation-cap',
    target: 20,
    xpReward: 500,
    coinsReward: 200,
  },
  {
    id: 'practice_1',
    category: 'rendimiento',
    title: 'Primera Práctica',
    description: 'Completa tu primera sesión de práctica por área',
    icon: 'bolt',
    target: 1,
    xpReward: 80,
    coinsReward: 40,
  },
  {
    id: 'practice_5',
    category: 'rendimiento',
    title: 'Practicante Constante',
    description: 'Completa 5 sesiones de práctica',
    icon: 'chart-line',
    target: 5,
    xpReward: 250,
    coinsReward: 120,
  },
  {
    id: 'perf_1',
    category: 'rendimiento',
    title: 'Mente Brillante',
    description: 'Obtén 100% en un examen o práctica',
    icon: 'brain',
    target: 1,
    xpReward: 300,
    coinsReward: 150,
  },
  {
    id: 'exam_1',
    category: 'rendimiento',
    title: 'Simulacro Completo',
    description: 'Finaliza tu primer simulacro ICFES completo',
    icon: 'clipboard-list',
    target: 1,
    xpReward: 400,
    coinsReward: 200,
  },
] as const;
