export const ACHIEVEMENTS_LIGAS = [
  {
    id: 'league_explorador',
    category: 'ligas',
    group: 'ligas_clasificatoria',
    title: 'Liga Explorador',
    description: 'Ascendiste a la liga Explorador en la clasificatoria',
    icon: 'map',
    target: 1,
    xpReward: 150,
    coinsReward: 75,
  },
  {
    id: 'league_aprendiz',
    category: 'ligas',
    group: 'ligas_clasificatoria',
    title: 'Liga Aprendiz',
    description: 'Ascendiste a la liga Aprendiz en la clasificatoria',
    icon: 'book-open',
    target: 1,
    xpReward: 200,
    coinsReward: 100,
  },
  {
    id: 'league_competente',
    category: 'ligas',
    group: 'ligas_clasificatoria',
    title: 'Liga Competente',
    description: 'Ascendiste a la liga Competente en la clasificatoria',
    icon: 'lightbulb',
    target: 1,
    xpReward: 300,
    coinsReward: 150,
  },
  {
    id: 'league_avanzado',
    category: 'ligas',
    group: 'ligas_clasificatoria',
    title: 'Liga Avanzado',
    description: 'Ascendiste a la liga Avanzado en la clasificatoria',
    icon: 'bolt',
    target: 1,
    xpReward: 400,
    coinsReward: 200,
  },
  {
    id: 'league_experto',
    category: 'ligas',
    group: 'ligas_clasificatoria',
    title: 'Liga Experto',
    description: 'Ascendiste a la liga Experto en la clasificatoria',
    icon: 'fire',
    target: 1,
    xpReward: 500,
    coinsReward: 250,
  },
  {
    id: 'league_maestro',
    category: 'ligas',
    group: 'ligas_clasificatoria',
    title: 'Liga Maestro',
    description: 'Llegaste a la liga Maestro, el nivel más alto',
    icon: 'crown',
    target: 1,
    xpReward: 1000,
    coinsReward: 500,
  },
] as const;
