export const SUPPORT_REPORT_ACHIEVEMENT_IDS = [
  'support_rep_1',
  'support_rep_3',
  'support_rep_5',
  'support_rep_10',
] as const;

export const PROFILE_REPORT_ACHIEVEMENT_IDS = [
  'profile_rep_1',
  'profile_rep_3',
  'profile_rep_5',
  'profile_rep_10',
] as const;

export const ACHIEVEMENTS_SUPPORT_REPORTS = [
  {
    id: 'support_rep_1',
    category: 'metas' as const,
    group: 'metas_reportes_soporte',
    title: 'Ojos de águila I',
    description: 'Ten 1 reporte de soporte aceptado por el equipo',
    icon: 'bug',
    target: 1,
    xpReward: 150,
    coinsReward: 75,
  },
  {
    id: 'support_rep_3',
    category: 'metas' as const,
    group: 'metas_reportes_soporte',
    title: 'Ojos de águila II',
    description: 'Ten 3 reportes de soporte aceptados',
    icon: 'search',
    target: 3,
    xpReward: 300,
    coinsReward: 150,
  },
  {
    id: 'support_rep_5',
    category: 'metas' as const,
    group: 'metas_reportes_soporte',
    title: 'Ojos de águila III',
    description: 'Ten 5 reportes de soporte aceptados',
    icon: 'eye',
    target: 5,
    xpReward: 500,
    coinsReward: 250,
  },
  {
    id: 'support_rep_10',
    category: 'metas' as const,
    group: 'metas_reportes_soporte',
    title: 'Ojos de águila IV',
    description: 'Ten 10 reportes de soporte aceptados',
    icon: 'shield-alt',
    target: 10,
    xpReward: 800,
    coinsReward: 400,
  },
] as const;

export const ACHIEVEMENTS_PROFILE_REPORTS = [
  {
    id: 'profile_rep_1',
    category: 'metas' as const,
    group: 'metas_reportes_perfil',
    title: 'Guardián I',
    description: 'Ten 1 reporte de perfil aceptado por el equipo',
    icon: 'flag',
    target: 1,
    xpReward: 150,
    coinsReward: 75,
  },
  {
    id: 'profile_rep_3',
    category: 'metas' as const,
    group: 'metas_reportes_perfil',
    title: 'Guardián II',
    description: 'Ten 3 reportes de perfil aceptados',
    icon: 'user-shield',
    target: 3,
    xpReward: 300,
    coinsReward: 150,
  },
  {
    id: 'profile_rep_5',
    category: 'metas' as const,
    group: 'metas_reportes_perfil',
    title: 'Guardián III',
    description: 'Ten 5 reportes de perfil aceptados',
    icon: 'shield-alt',
    target: 5,
    xpReward: 500,
    coinsReward: 250,
  },
  {
    id: 'profile_rep_10',
    category: 'metas' as const,
    group: 'metas_reportes_perfil',
    title: 'Guardián IV',
    description: 'Ten 10 reportes de perfil aceptados',
    icon: 'crown',
    target: 10,
    xpReward: 800,
    coinsReward: 400,
  },
] as const;
