export const ACHIEVEMENTS_DATA = [
  {
    id: 'study_1',
    category: 'estudio',
    title: 'Primeros Pasos',
    description: 'Completa tus primeras 5 lecciones',
    icon: 'book',
    target: 5,
    xpReward: 100,
    coinsReward: 50,
  },
  {
    id: 'study_2',
    category: 'estudio',
    title: 'Estudiante Dedicado',
    description: 'Completa 20 lecciones',
    icon: 'graduation-cap',
    target: 20,
    xpReward: 500,
    coinsReward: 200,
  },
  {
    id: 'practice_1',
    category: 'rendimiento',
    title: 'Primera Práctica',
    description: 'Completa tu primera sesión de práctica por área',
    icon: 'bolt',
    target: 1,
    xpReward: 80,
    coinsReward: 40,
  },
  {
    id: 'practice_5',
    category: 'rendimiento',
    title: 'Practicante Constante',
    description: 'Completa 5 sesiones de práctica',
    icon: 'chart-line',
    target: 5,
    xpReward: 250,
    coinsReward: 120,
  },
  {
    id: 'perf_1',
    category: 'rendimiento',
    title: 'Mente Brillante',
    description: 'Obtén 100% en un examen o práctica',
    icon: 'brain',
    target: 1,
    xpReward: 300,
    coinsReward: 150,
  },
  {
    id: 'exam_1',
    category: 'rendimiento',
    title: 'Simulacro Completo',
    description: 'Finaliza tu primer simulacro ICFES completo',
    icon: 'clipboard-list',
    target: 1,
    xpReward: 400,
    coinsReward: 200,
  },
  {
    id: 'const_1',
    category: 'constancia',
    title: 'Racha de Fuego',
    description: 'Mantén una racha de 7 días',
    icon: 'fire',
    target: 7,
    xpReward: 200,
    coinsReward: 100,
  },
  {
    id: 'meta_1',
    category: 'metas',
    title: 'Maestro del ICFES',
    description: 'Alcanza el nivel 5',
    icon: 'trophy',
    target: 5,
    xpReward: 1000,
    coinsReward: 500,
  },
  {
    id: 'time_1',
    category: 'constancia',
    title: 'Maratón de Estudio',
    description: 'Estudia durante 2 horas seguidas',
    icon: 'clock',
    target: 120,
    xpReward: 150,
    coinsReward: 75,
  },
  {
    id: 'read_importancia',
    category: 'lectura',
    title: 'Importancia leída',
    description: 'Marca como leída la sección Importancia en Lectura',
    icon: 'info-circle',
    target: 1,
    xpReward: 50,
    coinsReward: 25,
  },
  {
    id: 'read_informacion',
    category: 'lectura',
    title: 'Información leída',
    description: 'Marca como leída la sección Información en Lectura',
    icon: 'clipboard-list',
    target: 1,
    xpReward: 50,
    coinsReward: 25,
  },
  {
    id: 'read_consejos',
    category: 'lectura',
    title: 'Consejos leídos',
    description: 'Marca como leída la sección Consejos en Lectura',
    icon: 'lightbulb',
    target: 1,
    xpReward: 50,
    coinsReward: 25,
  },
  {
    id: 'league_explorador',
    category: 'ligas',
    title: 'Liga Explorador',
    description: 'Ascendiste a la liga Explorador en la clasificatoria',
    icon: 'map',
    target: 1,
    xpReward: 150,
    coinsReward: 75,
  },
  {
    id: 'league_aprendiz',
    category: 'ligas',
    title: 'Liga Aprendiz',
    description: 'Ascendiste a la liga Aprendiz en la clasificatoria',
    icon: 'book-open',
    target: 1,
    xpReward: 200,
    coinsReward: 100,
  },
  {
    id: 'league_competente',
    category: 'ligas',
    title: 'Liga Competente',
    description: 'Ascendiste a la liga Competente en la clasificatoria',
    icon: 'lightbulb',
    target: 1,
    xpReward: 300,
    coinsReward: 150,
  },
  {
    id: 'league_avanzado',
    category: 'ligas',
    title: 'Liga Avanzado',
    description: 'Ascendiste a la liga Avanzado en la clasificatoria',
    icon: 'bolt',
    target: 1,
    xpReward: 400,
    coinsReward: 200,
  },
  {
    id: 'league_experto',
    category: 'ligas',
    title: 'Liga Experto',
    description: 'Ascendiste a la liga Experto en la clasificatoria',
    icon: 'fire',
    target: 1,
    xpReward: 500,
    coinsReward: 250,
  },
  {
    id: 'league_maestro',
    category: 'ligas',
    title: 'Liga Maestro',
    description: 'Llegaste a la liga Maestro, el nivel más alto',
    icon: 'crown',
    target: 1,
    xpReward: 1000,
    coinsReward: 500,
  },
] as const;

export const ACHIEVEMENT_CATEGORIES = {
  all: { label: 'Todos', icon: 'star' },
  estudio: { label: 'Estudio', icon: 'book' },
  rendimiento: { label: 'Rendimiento', icon: 'bolt' },
  constancia: { label: 'Constancia', icon: 'fire' },
  metas: { label: 'Metas', icon: 'trophy' },
  lectura: { label: 'Lectura', icon: 'book-open' },
  ligas: { label: 'Ligas', icon: 'trophy' },
} as const;

/** IDs de logros otorgados al ascender de liga (job semanal). */
export const LEAGUE_ACHIEVEMENT_IDS: Record<string, string> = {
  explorador: 'league_explorador',
  aprendiz: 'league_aprendiz',
  competente: 'league_competente',
  avanzado: 'league_avanzado',
  experto: 'league_experto',
  maestro: 'league_maestro',
};

export type AchievementCategoryKey = keyof typeof ACHIEVEMENT_CATEGORIES;
