import type { LegacyLessonEntry } from './types';

export const LEGACY_LESSON_CONTENT: Record<string, Record<string, LegacyLessonEntry>> = {
  matematicas: {
    algebra: {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-math-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Fundamentos de Álgebra Avanzada',
        duration: '6-7 horas',
        lessons: 28,
        difficulty: 'fácil-medio',
        topics: [
          {
            name: 'Ecuaciones Lineales',
            description:
              'Aprende a resolver ecuaciones de primer grado con una o más variables. ' +
              'Dominando técnicas de despeje y balanceo.',
            subtopics: [
              'Ecuaciones con una variable',
              'Ecuaciones con dos variables',
              'Sistemas de ecuaciones lineales',
              'Métodos de solución (sustitución, eliminación)',
            ],
            examples: ['2x + 5 = 13 → x = 4', '3x - 2y = 5 combinado con x + y = 4'],
          },
          {
            name: 'Sistemas de Ecuaciones',
            description: 'Resuelve conjuntos de ecuaciones simultáneamente usando múltiples métodos.',
            subtopics: ['Métodos de sustitución', 'Métodos de eliminación', 'Métodos gráficos', 'Sistemas 2x2 y 3x3'],
            examples: [
              'Sistema con solución única',
              'Sistema sin solución (inconsistente)',
              'Sistema con infinitas soluciones (dependiente)',
            ],
          },
          {
            name: 'Polinomios',
            description: 'Operaciones y factorización de expresiones algebraicas polinómicas.',
            subtopics: [
              'Suma, resta, multiplicación de polinomios',
              'Factorización básica',
              'Trinomios cuadráticos',
              'División sintética',
            ],
            examples: ['(x + 2)(x - 3) = x² - x - 6', 'x² + 5x + 6 = (x + 2)(x + 3)', 'Factorización por agrupación'],
          },
        ],
        keyFormulas: [
          'ax + b = 0 → x = -b/a',
          '(a + b)² = a² + 2ab + b²',
          '(a - b)² = a² - 2ab + b²',
          'a² - b² = (a + b)(a - b)',
        ],
        practiceExercises: [
          'Resolver 5x - 3 = 2x + 9',
          'Encontrar x e y: x + y = 7, 2x - y = 5',
          'Factorizar x² + 7x + 12',
          'Expandir (2x - 3)²',
        ],
      },
    },
    geometria: {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-math-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Geometría Euclidiana y Espacial',
        duration: '7-8 horas',
        lessons: 26,
        difficulty: 'fácil-medio',
        topics: [
          {
            name: 'Triángulos',
            description: 'Propiedades, clasificación y cálculos con triángulos en el plano.',
            subtopics: [
              'Clasificación por lados (equilátero, isósceles, escaleno)',
              'Clasificación por ángulos (acutángulo, obtusángulo, rectángulo)',
              'Teorema de Pitágoras',
              'Áreas y perímetros',
            ],
            examples: ['Triángulo rectángulo: a² + b² = c²', 'Área = (base × altura) / 2', 'Perímetro = a + b + c'],
          },
          {
            name: 'Círculos',
            description: 'Elementos del círculo, circunferencia y cálculos de área.',
            subtopics: ['Radio, diámetro, cuerda', 'Circunferencia y arco', 'Área del círculo', 'Sectores y segmentos'],
            examples: ['Circunferencia = 2πr', 'Área = πr²', 'Diámetro = 2 × radio'],
          },
          {
            name: 'Volúmenes',
            description: 'Cálculo de volúmenes para sólidos geométricos comunes.',
            subtopics: ['Prismas y paralelepípedos', 'Cilindros', 'Esferas', 'Conos y pirámides'],
            examples: ['Cubo: V = a³', 'Cilindro: V = πr²h', 'Esfera: V = (4/3)πr³'],
          },
        ],
        keyFormulas: [
          'Área triángulo = (b × h) / 2',
          'Circunferencia = 2πr',
          'Área círculo = πr²',
          'Volumen cubo = a³',
          'Volumen cilindro = πr²h',
        ],
        practiceExercises: [
          'Encontrar el área de un triángulo con base 10 cm y altura 8 cm',
          'Calcular la circunferencia de un círculo con radio 5 cm',
          'Encontrar el volumen de una esfera con radio 3 cm',
          'Usar teorema de Pitágoras: lados 3 y 4, hallar hipotenusa',
        ],
      },
    },
    calculo: {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-math-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Cálculo Diferencial e Integral',
        duration: '10-12 horas',
        lessons: 30,
        difficulty: 'muy difícil',
        topics: [
          {
            name: 'Límites',
            description: 'Concepto fundamental de límites y continuidad de funciones.',
            subtopics: [
              'Definición de límite',
              'Límites laterales',
              'Continuidad y discontinuidad',
              'Límites infinitos y en el infinito',
            ],
            examples: ['lim(x→2) (x² + 1) = 5', 'lim(x→∞) 1/x = 0', 'Función continua en un punto'],
          },
          {
            name: 'Derivadas',
            description: 'Concepto de derivada y cálculo de derivadas de funciones.',
            subtopics: ['Definición de derivada', 'Regla de potencia', 'Regla del producto', 'Regla de la cadena'],
            examples: ['d/dx(x²) = 2x', 'd/dx(x³ + 2x) = 3x² + 2', 'Regla de la cadena: d/dx(u²) = 2u(du/dx)'],
          },
          {
            name: 'Aplicaciones',
            description: 'Aplicaciones de derivadas en optimización y análisis de funciones.',
            subtopics: [
              'Valores máximos y mínimos',
              'Análisis de concavidad',
              'Problemas de optimización',
              'Tasas de cambio',
            ],
            examples: [
              'Encontrar máximos de f(x) = -x² + 4x',
              'Determinar intervalos de crecimiento',
              'Problemas de área y volumen máximo',
            ],
          },
        ],
        keyFormulas: [
          "f'(x) = lim(h→0) [f(x+h) - f(x)]/h",
          'd/dx(xⁿ) = nxⁿ⁻¹',
          "d/dx(u·v) = u'v + uv'",
          "d/dx(u/v) = (u'v - uv')/v²",
        ],
        practiceExercises: [
          'Calcular lim(x→3) (x² - 9)/(x - 3)',
          'Encontrar la derivada de f(x) = 5x³ - 2x² + x',
          'Aplicar regla de la cadena: f(x) = (3x + 1)⁴',
          'Encontrar máximos de f(x) = 3x² - 12x + 5',
        ],
      },
    },
    trigonometria: {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-math-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Trigonometría Avanzada',
        duration: '7-8 horas',
        lessons: 24,
        difficulty: 'medio-alto',
        topics: [
          {
            name: 'Funciones Trigonométricas',
            description: 'Seno, coseno y tangente en triángulos rectángulos y en el círculo unitario.',
            subtopics: [
              'Seno, coseno y tangente',
              'Cotangente, secante y cosecante',
              'Círculo unitario',
              'Radianes y grados',
            ],
            examples: ['sin(30°) = 1/2, cos(30°) = √3/2', 'tan(45°) = 1', 'sen(π/2) = 1'],
          },
          {
            name: 'Identidades Trigonométricas',
            description: 'Relaciones fundamentales y derivadas entre funciones trigonométricas.',
            subtopics: [
              'Identidades pitagóricas',
              'Identidades suma y diferencia',
              'Identidades doble ángulo',
              'Simplificación de expresiones',
            ],
            examples: ['sen²θ + cos²θ = 1', 'sen(α ± β) = senα cosβ ± cosα senβ', 'sen(2θ) = 2senθ cosθ'],
          },
          {
            name: 'Ecuaciones Trigonométricas',
            description: 'Resolución de ecuaciones que contienen funciones trigonométricas.',
            subtopics: [
              'Ecuaciones simples',
              'Ecuaciones con múltiples ángulos',
              'Factorización',
              'Soluciones en intervalo dado',
            ],
            examples: ['senx = 1/2, x = π/6 + 2πk', 'cos(2x) = cos(x)', '2senx - 1 = 0'],
          },
        ],
        keyFormulas: [
          'sen(θ) = opuesto/hipotenusa',
          'cos(θ) = adyacente/hipotenusa',
          'tan(θ) = opuesto/adyacente',
          'sen²θ + cos²θ = 1',
          'sen(α ± β) = senα cosβ ± cosα senβ',
        ],
        practiceExercises: [
          'Encontrar sin(60°), cos(60°), tan(60°)',
          'Simplificar: sen²x + cos²x + tan²x csc²x',
          'Resolver: 2cos(x) = √2 en [0, 2π)',
          'Calcular: sin(75°) usando fórmula de suma',
        ],
      },
    },
    'numeros-complejos': {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-math-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Números Complejos y Álgebra Compleja',
        duration: '6-7 horas',
        lessons: 22,
        difficulty: 'muy difícil',
        topics: [
          {
            name: 'Operaciones Complejas',
            description: 'Suma, resta, multiplicación y división de números complejos.',
            subtopics: [
              'Números imaginarios',
              'Forma binómica a + bi',
              'Suma y resta de complejos',
              'Multiplicación y división',
            ],
            examples: ['i² = -1', '(3 + 2i) + (1 - i) = 4 + i', '(2 + i)(3 - 2i) = 8 - i'],
          },
          {
            name: 'Forma Polar',
            description: 'Representación de números complejos en forma polar.',
            subtopics: [
              'Módulo y argumento',
              'Conversión cartesiana a polar',
              'Forma r(cosθ + isenθ)',
              'Representación geométrica',
            ],
            examples: ['|z| = √(a² + b²)', 'z = 3 + 4i → |z| = 5', 'Forma polar: z = r(cosθ + isenθ)'],
          },
          {
            name: 'Teorema de De Moivre',
            description: 'Potenciación y radicación de números complejos.',
            subtopics: [
              'Potencias de números complejos',
              'Raíces n-ésimas',
              'Aplicaciones en resolución de ecuaciones',
              'Fórmula de Euler',
            ],
            examples: ['[r(cosθ + isenθ)]ⁿ = rⁿ(cosnθ + isennθ)', 'Encontrar √(1 + i)', 'Resolver z³ = 8'],
          },
        ],
        keyFormulas: [
          'i² = -1',
          '|a + bi| = √(a² + b²)',
          '(a + bi) + (c + di) = (a+c) + (b+d)i',
          'z = r(cosθ + isenθ)',
          '[r(cosθ + isenθ)]ⁿ = rⁿ(cosnθ + isennθ)',
        ],
        practiceExercises: [
          'Calcular (2 + 3i)(1 - 2i)',
          'Encontrar el módulo de 3 - 4i',
          'Convertir 1 + i a forma polar',
          'Resolver z² = -4',
        ],
      },
    },
  },
  lenguaje: {
    gramatica: {
      glowA: 'lesson-lc-glow-a',
      glowB: 'lesson-lc-glow-b',
      keySectionTitle: 'Conceptos Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Gramática Española',
        duration: '8-9 horas',
        lessons: 28,
        difficulty: 'medio',
        topics: [
          {
            name: 'Verbos: Conjugación y Uso',
            description: 'Estudio exhaustivo de clasificación, conjugación y usos avanzados de verbos en español.',
            subtopics: [
              'Verbos regulares e irregulares',
              'Tiempos verbales (presente, pasado, futuro)',
              'Modos (indicativo, subjuntivo, imperativo, condicional)',
              'Verbos reflexivos y recíprocos',
              'Verbos pronominales',
              'Conjugación perifrástica (ir a + infinitivo)',
              'Voz pasiva y activa',
              'Participios y gerundios',
              'Tiempos perfectos (compuestos)',
              'Aspecto perfecto e imperfecto',
            ],
            examples: [
              'Regular: Hablar: hablo, hablas, habla, hablamos, habláis, hablan',
              'Irregular: Ser: soy, eres, es, somos, sois, son',
              'Ir: voy, vas, va, vamos, vais, van',
              'Estar: estoy, estás, está, estamos, estáis, están',
              'Tener: tengo, tienes, tiene, tenemos, tenéis, tienen',
              'Verbos reflexivos: lavarse, levantarse, acostarse',
              'Perifrástica: "Voy a estudiar" (futuro próximo)',
              'Pasiva: "El libro fue escrito por María"',
              'Activa: "María escribió el libro"',
              'Gerundio: "Estudiando aprenderás" (participio presente)',
            ],
          },
          {
            name: 'Sustantivos y Adjetivos',
            description: 'Análisis profundo de clasificación, género, número y concordancia.',
            subtopics: [
              'Género (masculino, femenino, neutro)',
              'Número (singular, plural)',
              'Adjetivos calificativos',
              'Adjetivos determinativos (demostrativos, posesivos, indefinidos)',
              'Adjetivos comparativos y superlativos',
              'Concordancia de género y número',
              'Sustantivos contables e incontables',
              'Sustantivos propios y comunes',
              'Sustantivos colectivos',
              'Apócope de adjetivos',
            ],
            examples: [
              'El gato negro - La casa grande',
              'Plural: niño→niños, casa→casas, luz→luces, actor→actores',
              'Concordancia: mujer inteligente, hombres inteligentes',
              'Demostrativo: este, ese, aquel',
              'Posesivo: mi, tu, su, nuestro, vuestro',
              'Indefinido: algún, ningún, todo, otro',
              'Comparativo: más grande que, menos bonito que',
              'Superlativo: el más grande, bellísimo',
              'Apócope: "un" (antes de sustantivo masculino), "buen" (antes de sustantivo)',
            ],
          },
          {
            name: 'Conjugaciones Verbales Detalladas',
            description: 'Patrones completos de conjugación en los tres grupos y formas irregulares.',
            subtopics: [
              'Primera conjugación (-ar): amar, hablar, comprar',
              'Segunda conjugación (-er): comer, beber, temer',
              'Tercera conjugación (-ir): vivir, partir, recibir',
              'Tiempos simples: presente, pretérito, futuro, condicional',
              'Tiempos compuestos: perfectos, pluscuamperfecto',
              'Presente: radical + terminación',
              'Pretérito imperfecto',
              'Pretérito indefinido (perfecto simple)',
              'Conjugación subjuntiva',
              'Formas no personales: infinitivo, gerundio, participio',
            ],
            examples: [
              'Presente: Yo hablo, tú hablas, él habla, nosotros hablamos, vosotros habláis, ellos hablan',
              'Pretérito indefinido: Hablé, hablaste, habló, hablamos, hablasteis, hablaron',
              'Pretérito imperfecto: Hablaba, hablabas, hablaba, hablábamos, hablabais, hablaban',
              'Futuro: Hablaré, hablarás, hablará, hablaremos, hablaréis, hablarán',
              'Condicional: Hablaría, hablarías, hablaría, hablaríamos, hablaríais, hablarían',
              'Presente subjuntivo: Hable, hables, hable, hablemos, habléis, hablen',
              'Imperativo: habla, hable, hablemos, hablad, hablen',
            ],
          },
          {
            name: 'Pronombres y Relaciones Pronominales',
            description: 'Análisis de tipos de pronombres y su correcto uso en construcciones sintácticas.',
            subtopics: [
              'Pronombres personales: sujeto, objeto directo, indirecto',
              'Pronombres reflexivos',
              'Pronombres relativos (que, quien, cual, cuyo)',
              'Pronombres demostrativos',
              'Pronombres posesivos',
              'Pronombres indefinidos',
              'Pronombres interrogativos',
              'Pronombres enclíticos y proclíticos',
              'Orden de pronombres átonos',
              'Leísmo, loísmo, laísmo',
            ],
            examples: [
              'Sujeto: Yo, tú, él, nosotros, vosotros, ellos',
              'Objeto directo: me, te, lo, la, nos, os, los, las',
              'Objeto indirecto: me, te, le, nos, os, les',
              'Reflexivos: me, te, se, nos, os',
              'Relativos: El libro que leí, la persona quien vino',
              'Orden correcto: Se lo dije (no Se dije lo)',
              'Enclíticos: Dímelo, hazlo, cómpralo',
              'Proclíticos: Me lo diste, nos lo prometiste',
            ],
          },
          {
            name: 'Oraciones Complejas y Análisis Sintáctico',
            description: 'Estudio de estructura oracional, coordinación y subordinación.',
            subtopics: [
              'Oraciones simples',
              'Oraciones compuestas (coordinadas, subordinadas)',
              'Coordinación por conjunciones: y, o, pero, sino',
              'Subordinación: causal, temporal, condicional, final, concesiva',
              'Cláusulas relativas',
              'Análisis de sujeto y predicado',
              'Complementos del verbo (directo, indirecto, circunstancial)',
              'Concordancia sujeto-verbo',
              'Ambigüedad sintáctica',
              'Construcciones con infinitivo y gerundio',
            ],
            examples: [
              'Simple: "María estudia Ingeniería"',
              'Coordinada: "María estudia y Juan trabaja"',
              'Subordinada causal: "Llegó tarde porque se perdió"',
              'Subordinada temporal: "Cuando termine, te llamo"',
              'Subordinada condicional: "Si llueve, no iremos"',
              'Relativa: "El estudiante que ganó es mi amigo"',
              'Complemento directo: "Vi a María ayer"',
              'Complemento indirecto: "Le dije la verdad"',
              'Circunstancial de lugar: "Vivo en Madrid"',
            ],
          },
        ],
        keyFormulas: [
          'Presente regular: raíz + terminación presente',
          'Pretérito: raíz + terminación especial (-é, -aste, -ó)',
          'Futuro: infinitivo + terminación futura',
          'Sustantivo + adjetivo = concordancia en género y número',
          'Verbo + pronombre = colocación correcta del pronombre',
          'Oración simple = sujeto + predicado',
          'Oración compuesta = múltiples verbos conjugados',
        ],
        practiceExercises: [
          'Conjugar verbos regulares e irregulares en todos los tiempos',
          'Hacer concordancia: El día (soleado/soleada/soleados)',
          'Identificar y corregir errores de concordancia',
          'Análisis sintáctico: sujeto, predicado y complementos',
          'Transformar oraciones: activa a pasiva y viceversa',
          'Conjugar "ser, estar, tener, haber" en todos los tiempos',
          'Identificar verbos irregulares: ser, ir, estar, tener, haber, venir, salir',
          'Colocar pronombres correctamente en oraciones',
          'Crear oraciones complejas con coordinación y subordinación',
          'Reconocer tipos de subordinadas por su función',
          'Diferenciar entre gerundio, participio e infinitivo',
          'Ejercicios de transformación: cambio de tiempo y modo',
        ],
      },
    },
    comprension: {
      glowA: 'lesson-lc-glow-a',
      glowB: 'lesson-lc-glow-b',
      keySectionTitle: 'Estrategias Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Comprensión Lectora',
        duration: '7-8 horas',
        lessons: 25,
        difficulty: 'medio',
        topics: [
          {
            name: 'Análisis de Textos',
            description:
              'Técnicas avanzadas para identificar ideas principales, secundarias y propósito comunicativo del texto.',
            subtopics: [
              'Idea principal vs secundarias',
              'Propósito del autor',
              'Estructura del texto (inicio, desarrollo, conclusión)',
              'Tema e intención comunicativa',
              'Coherencia y cohesión textual',
              'Conectores y enlaces',
              'Tipos de párrafos (narrativo, argumentativo, descriptivo, expositivo)',
              'Topografía del texto',
            ],
            examples: [
              'Párrafo narrativo: ¿qué sucede? (hechos, acciones, eventos)',
              'Párrafo argumentativo: ¿qué intenta demostrar? (tesis, argumentos, conclusión)',
              'Párrafo descriptivo: ¿qué se describe? (características, cualidades)',
              'Párrafo expositivo: ¿qué se explica? (información, conceptos)',
              'Idea principal en noticia: primer párrafo resume la noticia',
              'Idea secundaria: detalles que complementan la principal',
            ],
          },
          {
            name: 'Inferencias y Deducción',
            description: 'Desarrollo de habilidades para deducir información implícita y hacer conclusiones lógicas.',
            subtopics: [
              'Inferencias por contexto',
              'Significado de palabras desconocidas por contexto',
              'Conclusiones lógicas basadas en evidencia',
              'Predecir continuaciones y desenlaces',
              'Análisis de causa y efecto',
              'Reconocimiento de supuestos implícitos',
              'Interpretación de tonalidad y actitud del autor',
              'Deducción de características de personajes',
            ],
            examples: [
              'Texto: "Era una noche fría y oscura, el viento aullaba entre las calles"',
              'Inferencia: contexto sombrío/misterioso/atemorizante',
              'Deducción: probablemente ocurrirá algo inquietante',
              'Causa: el frío extremo → Efecto: la gente se quedó en casa',
              'Supuesto implícito: si alguien cierra puertas y ventanas → tiene miedo',
              'Tonalidad: de horror, misterio, suspense',
            ],
          },
          {
            name: 'Vocabulario Contextual',
            description: 'Técnicas para determinar significados de palabras según el contexto y ampliar vocabulario.',
            subtopics: [
              'Sinónimos y antónimos en contexto',
              'Palabras polisémicas (múltiples significados)',
              'Expresiones idiomáticas',
              'Campos semánticos',
              'Palabras homógrafas y homófonas',
              'Raíces etimológicas',
              'Prefijos y sufijos',
              'Registros lingüísticos',
            ],
            examples: [
              'Banco (asiento vs institución vs corriente marina)',
              'Contexto determina significado: "El banco está junto al río"',
              'Expresiones: "llorar a mares" (llorar mucho), "costar un ojo de la cara" (muy caro)',
              'Campo semántico de TRANSPORTE: coche, autobús, tren, avión, barco',
              'Homógrafas: vela (prenda) vs vela (acción de velar)',
              'Prefijo re-: repetir, reconstruir, regresar',
            ],
          },
          {
            name: 'Tipos de Texto y Géneros',
            description: 'Análisis y características de diferentes tipos de textos literarios y no literarios.',
            subtopics: [
              'Textos narrativos (cuento, novela, crónica)',
              'Textos descriptivos',
              'Textos argumentativos',
              'Textos expositivos',
              'Textos informativos (noticias, reportajes)',
              'Textos instructivos',
              'Literatura infantil vs juvenil vs adulta',
              'Análisis de diálogos',
            ],
            examples: [
              'Narrativo: "Cuando María llegó a casa, encontró la puerta abierta"',
              'Descriptivo: "La casa era grande, con ventanas de madera y puertas de metal"',
              'Argumentativo: "Los smartphones son perjudiciales porque reducen la concentración"',
              'Instructivo: "Para preparar café, hierva agua y agregue café molido"',
            ],
          },
          {
            name: 'Estrategias de Lectura Crítica',
            description: 'Técnicas para analizar críticamente textos, identificar sesgos y evaluar credibilidad.',
            subtopics: [
              'Lectura exploratoria',
              'Lectura selectiva',
              'Lectura profunda/crítica',
              'Identificación de sesgos y prejuicios',
              'Evaluación de fuentes',
              'Análisis de la intencionalidad',
              'Reconocimiento de hechos vs opiniones',
              'Análisis de perspectivas contradictorias',
            ],
            examples: [
              'Sesgo: "Los políticos siempre mienten" (generalización)',
              'Hecho: "La ciudad tuvo 25 grados de temperatura ayer"',
              'Opinión: "Fue un día hermoso"',
              'Fuente confiable: artículo con referencias científicas',
              'Fuente no confiable: afirmaciones sin evidencia',
            ],
          },
        ],
        keyFormulas: [
          'Idea principal = respuesta a ¿de qué trata el texto?',
          'Inferencia = información implícita basada en evidencia contextual',
          'Contexto = claves para significados desconocidos',
          'Propósito = objetivo comunicativo del autor (informar, persuadir, entretener, instruir)',
          'Coherencia = relación lógica entre ideas',
          'Causa y Efecto = ¿por qué sucede? ¿qué sucede como resultado?',
        ],
        practiceExercises: [
          'Leer párrafos e identificar idea principal, secundarias y propósito',
          'Hacer inferencias sobre motivaciones y características de personajes',
          'Deducir significado de palabras desconocidas del contexto',
          'Identificar propósito textual: informar, persuadir, entretener, instruir',
          'Analizar relaciones de causa y efecto en textos narrativos',
          'Distinguir hechos de opiniones en textos argumentativos',
          'Crear mapas conceptuales de textos complejos',
          'Resumir textos identificando puntos clave',
          'Responder preguntas de comprensión profunda',
          'Analizar el tono y la actitud del autor',
        ],
      },
    },
    literatura: {
      glowA: 'lesson-lc-glow-a',
      glowB: 'lesson-lc-glow-b',
      keySectionTitle: 'Conceptos Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Literatura',
        duration: '10-11 horas',
        lessons: 30,
        difficulty: 'medio-alto',
        topics: [
          {
            name: 'Figuras Literarias y Recursos Estilísticos',
            description: 'Estudio exhaustivo de recursos retóricos para enriquecer la expresión literaria.',
            subtopics: [
              'Metáfora y comparación (símil)',
              'Hipérbole y litote',
              'Personificación (prosopopeya)',
              'Aliteración y onomatopeya',
              'Metonimia y sinécdoque',
              'Paradoja y oxímoron',
              'Ironía y sarcasmo',
              'Anáfora, epífrasis y quiasmo',
              'Hipérbaton y elipsis',
              'Juego de palabras y cacofonía',
            ],
            examples: [
              'Metáfora: "eres mi sol" (comparación implícita)',
              'Símil: "blanco como la nieve" (comparación explícita)',
              'Hipérbole: "te lo he dicho mil veces" (exageración)',
              'Litote: "no es malo" (atenuación)',
              'Personificación: "la noche suspiraba" (atributos humanos)',
              'Aliteración: "El susurro del silencio" (repetición de sonidos)',
              'Onomatopeya: "crac, pum, zzz" (imitación de sonidos)',
              'Metonimia: "Bebió dos copas" (recipiente por contenido)',
              'Sinécdoque: "Llegaron cien cabezas" (parte por todo)',
              'Paradoja: "menos es más" (contradicción aparente)',
              'Oxímoron: "hermoso horror" (palabra contradictoria)',
              'Ironía: Decir algo con intención opuesta al significado',
              'Anáfora: "Volverán las oscuras golondrinas" (repetición inicial)',
            ],
          },
          {
            name: 'Géneros Literarios Principales',
            description: 'Análisis profundo de características, tipos y ejemplos de géneros literarios.',
            subtopics: [
              'Narrativa: novela, cuento, crónica, fábula, leyenda',
              'Poesía: verso, prosa poética, poema épico',
              'Drama: tragedia, comedia, melodrama, tragicomedia',
              'Ensayo: formal, personal, científico',
              'Textos expositivos y descriptivos',
              'Subgéneros narrativos',
              'Estructura interna de géneros',
              'Voz narrativa y perspectiva',
              'Punto de vista del narrador',
              'Tiempo y espacio narrativo',
            ],
            examples: [
              'Novela: extensión variable, complejidad de caracteres, trama compleja',
              'Cuento: brevedad, concentración de la acción, desenlace sorpresivo',
              'Poesía: ritmo, rima, métrica, musicalidad',
              'Drama: diálogos, acciones, conflicto entre personajes',
              'Tragedia: final desgraciado, protagonista noble',
              'Comedia: final feliz, tono humorístico',
              'Ensayo: reflexión personal sobre tema',
              'Fábula: historia breve con moraleja',
              'Leyenda: narración tradicional, mezcla de real e imaginario',
              'Epopeya: poema narrativo de acciones heroicas',
            ],
          },
          {
            name: 'Autores Clásicos Hispanohablantes',
            description: 'Estudio profundo de obras y contribuciones de grandes escritores.',
            subtopics: [
              'Autores españoles medievales y renacentistas',
              'Autores españoles del Siglo de Oro',
              'Autores españoles modernistas y contemporáneos',
              'Autores latinoamericanos coloniales',
              'Autores latinoamericanos modernistas',
              'Autores latinoamericanos del siglo XX',
              'Autores hispanohablantes contemporáneos',
              'Movimientos literarios: Renacimiento, Barroco, Romanticismo, Realismo, Modernismo',
              'Contexto histórico y literario',
              'Influencias mutuas entre autores',
            ],
            examples: [
              'Quijote - Cervantes (novela moderna, sátira de libros de caballerías)',
              'Cien años de soledad - García Márquez (realismo mágico)',
              'La casa de Bernarda Alba - Lorca (drama moderno, represión social)',
              'Don Juan - José Zorrilla (drama romántico)',
              'Rimas - Gustavo Adolfo Bécquer (poesía romántica)',
              'El poema del Cid - Anónimo (poema épico medieval)',
              'La Celestina - Fernando de Rojas (tragicomedia renacentista)',
              'Campos de Castilla - Antonio Machado (poesía generación 98)',
              'Rayuela - Julio Cortázar (novela experimental)',
              'El laberinto de la soledad - Octavio Paz (ensayo)',
            ],
          },
          {
            name: 'Elementos de la Narrativa',
            description: 'Análisis detallado de componentes fundamentales de relatos literarios.',
            subtopics: [
              'Personajes: protagonista, antagonista, secundarios',
              'Caracterización: física, psicológica, social',
              'Desarrollo de personajes: estático vs dinámico',
              'Trama y argumento',
              'Nudo, desenlace y conflicto',
              'Tiempo narrativo: lineal, no lineal, circular',
              'Espacio: físico, psicológico, social',
              'Atmósfera y ambiente',
              'Voz narrativa: primera, segunda, tercera persona',
              'Narrador omnisciente, objetivo, limitado',
            ],
            examples: [
              'Protagonista: personaje principal',
              'Antagonista: se opone al protagonista',
              'Trama principal vs subtrama',
              'Conflicto externo: lucha contra enemigos/circunstancias',
              'Conflicto interno: lucha consigo mismo',
              'Tiempo lineal: narrativa cronológica',
              'Flashback: salto al pasado',
              'Prolepsis: adelanto de eventos futuros',
              'Espacio cerrado: casa, prison (claustrofóbico)',
              'Espacio abierto: campo, ciudad (libertad)',
            ],
          },
          {
            name: 'Análisis de Poesía',
            description: 'Técnicas para analizar y comprender poesía: métrica, rima, ritmo y significado.',
            subtopics: [
              'Métrica: sílabas, pies, versos',
              'Rima: consonante, asonante, libre',
              'Ritmo y cadencia',
              'Estrofas: cuarteta, terceto, soneto, lira',
              'Cesura y encabalgamiento',
              'Tema poético y voz lírica',
              'Registro poético: culto, popular',
              'Tonalidad: lírica, épica, satírica',
              'Poesía narrativa vs poesía lírica',
              'Interpretación y simbolismo',
            ],
            examples: [
              'Endecasílabo: verso de 11 sílabas',
              'Octosílabo: verso de 8 sílabas',
              'Rima consonante: gato-rato (suenan igual)',
              'Rima asonante: vino-sigo (solo vocales)',
              'Soneto: 14 versos en cuartetas y tercetos',
              'Lira: 5 versos de 7 y 11 sílabas',
              'Encabalgamiento: verso continúa en el siguiente',
              'Cesura: pausa dentro del verso',
              'Yo lírico: la voz del poeta en el poema',
              'Símbolo: palabra con significado adicional',
            ],
          },
        ],
        keyFormulas: [
          'Metáfora = comparación sin "como"',
          'Símil = comparación con "como"',
          'Aliteración = repetición de sonidos consonantes',
          'Genero literario = novela, drama, poesía, ensayo',
          'Trama = secuencia de eventos (qué sucede)',
          'Argumento = significado de los eventos (por qué importa)',
          'Métrica = estructura silábica del verso',
          'Rima = repetición de sonidos finales',
        ],
        practiceExercises: [
          'Identificar figuras literarias en textos y explicar su efecto',
          'Clasificar obras en géneros y justificar la clasificación',
          'Analizar estilo, lenguaje y técnicas de autores clásicos',
          'Crear ejemplos originales de figuras literarias',
          'Analizar la caracterización de personajes en obras',
          'Interpretar el significado simbólico de elementos narrativos',
          'Contar un acento: sílabas y clasificación de versos',
          'Identificar tipos de rima en poesía',
          'Analizar la estructura de estrofas (cuarteta, terceto, soneto)',
          'Comparar técnicas literarias entre autores diferentes',
          'Realizar análisis crítico de obras completas',
          'Escribir breves análisis literarios de fragmentos',
        ],
      },
    },
    ortografia: {
      glowA: 'lesson-lc-glow-a',
      glowB: 'lesson-lc-glow-b',
      keySectionTitle: 'Reglas Fundamentales',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Ortografía y Puntuación',
        duration: '6-7 horas',
        lessons: 24,
        difficulty: 'fácil-medio',
        topics: [
          {
            name: 'Reglas Ortográficas Complejas',
            description: 'Reglas exhaustivas para la escritura correcta de palabras en español.',
            subtopics: [
              'Uso de b/v: reglas diferenciadas',
              'Uso de c/s/z: contextos de uso',
              'Uso de g/j: reglas y excepciones',
              'Uso de h: palabras con h y sin h',
              'Uso de ll/y: distinción dialectal',
              'Palabras homófonas y parónimas',
              'Mayúsculas y minúsculas',
              'Divisiones silábicas',
              'Palabras de dudosa escritura',
              'Prefijos y sufijos ortográficos',
            ],
            examples: [
              'B vs V: Bello (bonito) vs vello (pelo), cabe (encaja) vs cava (vino)',
              'Regla B: verbos en -aba, -íamos; "ir al Baño"',
              'Regla V: sustantivos terminados en -ive, -ivo, -ividad',
              'C: ante a, o, u → casa, poco, cuanto',
              'Z: ante a, o, u → taza, pozo, zumo',
              'S: entre vocales → casa (no cassa)',
              'G: ante a, o, u → gato, goma, gusto',
              'G: ante e, i → gesto, gitano (g suave)',
              'J: siempre sonido fuerte → jarro, jirafa',
              'H: siempre muda → historia, hoja',
              'Palabras sin H: almohada (no alhomada)',
              'LL: sonido palatal → llama, llover',
              'Y: consonante y vocal → yo, yema; ayuda, raya',
              'Homófonas: Baya (fruta) vs vaya (ir) vs balla (danza medieval)',
              'Parónimas: Acción (hecho) vs acción (valor mobiliario), afección vs infección',
            ],
          },
          {
            name: 'Signos de Puntuación Avanzado',
            description: 'Uso exhaustivo y correcto de comas, puntos, guiones y otros signos.',
            subtopics: [
              'Punto (. período, punto y seguido)',
              'Coma (, ) en oraciones complejas',
              'Punto y coma (;) para separaciones',
              'Dos puntos (:) para enumeraciones',
              'Puntos suspensivos (...)',
              'Signos de exclamación (!)',
              'Signos de interrogación (?)',
              'Paréntesis, corchetes y llaves',
              'Guión, raya y diálogo',
              'Comillas y su uso correcto',
            ],
            examples: [
              'Punto: "María estudia. Juan trabaja." (separa oraciones independientes)',
              'Punto y seguido: "María estudia. Ella es inteligente." (mismo tema)',
              'Punto y aparte: (fin de párrafo)',
              'Oración compuesta: "María llegó; Juan se fue; Pedro se quedó."',
              'Coma enumerativa: "Necesito: lápiz, papel, goma y regla."',
              'Dos puntos antes de lista: "Ingredientes: harina, huevo, sal"',
              'Pausa media: "Aunque llueva, iremos al parque."',
              'Coma apositiva: "Mi hermano, el ingeniero, llegó ayer."',
              'Puntos suspensivos: "No sé qué decir... es extraño..."',
              'Signos de apertura y cierre: "¿Cuándo llegaste?" "¡Qué sorpresa!"',
              'Paréntesis aclarador: "García (de origen español) fue importante."',
              'Raya para diálogo: —Hola, ¿cómo estás? —Bien, gracias.',
            ],
          },
          {
            name: 'Acentuación y Tildación',
            description: 'Reglas completas de acento ortográfico y tildación en español.',
            subtopics: [
              'Palabras agudas, graves, esdrújulas, sobresdrújulas',
              'Reglas de acentuación para cada tipo',
              'Tilde diacrítica (para diferenciar palabras)',
              'Acentuación de diptongos y triptongos',
              'Hiatos vs diptongos',
              'Acentos en mayúsculas',
              'Acentuación de palabras compuestas',
              'Acentuación de formas verbales',
              'Palabras de acentuación dudosa',
              'Cambios recientes en las normas de acentuación',
            ],
            examples: [
              'Aguda (acento última sílaba): café, pintor, virtud (acentúa si termina en n, s, vocal)',
              'Grave (acento penúltimo): casa, árbol, claro (acentúa si no termina en n, s, vocal)',
              'Esdrújula (acento antepenúltimo): rápido, mágico, sábana (SIEMPRE tilde)',
              'Sobresdrújula (aún más atrás): Cómprale, explícamelo',
              'Diptongo: suave (no se divide)',
              'Hiato: caída (se divide: ca-í-da)',
              'Tilde diacrítica: té (bebida) vs te (pronombre)',
              'Más (preposición) vs más (adverbio de cantidad)',
              'Sé (verbo saber) vs se (pronombre)',
              'Mí (pronombre) vs mi (adjetivo)',
              'Tú (pronombre) vs tu (adjetivo)',
              'Él (pronombre) vs el (artículo)',
              'Cómo (pregunta/interrogativo) vs como (preposición/conjunción)',
              'Dónde (pregunta) vs donde (relativo)',
              'Cuándo (pregunta) vs cuando (conjunción)',
            ],
          },
          {
            name: 'Escritura de Números y Símbolos',
            description: 'Normas para escribir números, símbolos y abreviaturas.',
            subtopics: [
              'Números cardinales',
              'Números ordinales',
              'Números romanos',
              'Escritura de cantidades',
              'Dígitos vs palabras',
              'Decimales y porcentajes',
              'Símbolos matemáticos',
              'Unidades de medida',
              'Fechas y horas',
              'Abreviaturas comunes',
            ],
            examples: [
              'Cardinales: uno, dos, tres, veinti-, treinta, cuarenta',
              'Ordinales: primero, segundo, tercero, cuarto, quinto',
              'Romanos: I, II, III, IV, V, X, L, C, D, M',
              'Cantidad: "cinco dólares" o "5 dólares"',
              'Decimales: 3, 14 (español) vs 3.14 (inglés)',
              'Porcentaje: 25%, cincuenta por ciento',
              'Fecha: 10 de diciembre de 2025',
              'Hora: 14:30 (2:30 p.m.)',
              'Abreviaturas: Sr. (señor), Dra. (doctora), etc. (etcétera)',
              'Símbolos: @ (arroba), # (almohadilla), € (euro)',
            ],
          },
          {
            name: 'Errores Comunes y Correcciones',
            description: 'Identificación y corrección de faltas ortográficas frecuentes.',
            subtopics: [
              'Palabras mal tildadas',
              'Confusión de palabras homofonas',
              'Errores en verbos irregulares',
              'Mayúsculas innecesarias',
              'Uso incorrecto de puntuación',
              'Espacios en blanco',
              'Apostrofos incorrectos',
              'Barras y guiones mal colocados',
              'Palabras portmanteau mal escritas',
              'Cambios dialectales',
            ],
            examples: [
              'Mal: "haya vs alla" | Correcto: "haya (árbol) vs allá (adverbio de lugar)"',
              'Mal: "a favor vs afavor" | Correcto: "a favor (locución)"',
              'Mal: "ah vs a vs ha" | Correcto: distinción clara',
              'Mal: "sino vs si no" | Correcto: "sino (conjunción) vs si no (condicional)"',
              'Mal: "y vs e (antes de i)" | Correcto: "X e Y, pero "María y Iñigo"',
              'Mal: "bacilo vs basilico" | Correcto: distinción de significado',
              'Mal: "suscinto vs sucinto" | Correcto: sucinto (breve)',
              'Mal: "greña vs greña" | Correcto: greña (cabello desordenado)',
            ],
          },
        ],
        keyFormulas: [
          'Aguda: acento en última sílaba (regla: n, s, vocal)',
          'Grave: acento en penúltima sílaba (regla: no n, no s, no vocal)',
          'Esdrújula: acento SIEMPRE en antepenúltima sílaba',
          'Tilde diacrítica: distingue significados (té vs te)',
          'Coma enumerativa: separa elementos de una lista',
          'Punto y coma: pausa mayor que coma, menor que punto',
        ],
        practiceExercises: [
          'Corregir palabras mal escritas: haya vs alla, a favor vs afavor',
          'Colocar puntuación correcta a párrafos complejos',
          'Colocar tildes en palabras sin acento ortográfico',
          'Clasificar palabras por su acentuación (aguda, grave, esdrújula)',
          'Distinguir entre palabras homofonas: vaya-baya-valla',
          'Identificar errores de mayúsculas/minúsculas',
          'Usar correctamente signos de puntuación en textos',
          'Diferenciar diptongos de hiatos',
          'Aplicar reglas de tilde diacrítica',
          'Corregir oraciones con puntuación incorrecta',
          'Escribir números en letras o cifras según contexto',
          'Identificar y corregir acentuación en verbos',
        ],
      },
    },
    semantica: {
      glowA: 'lesson-lc-glow-a',
      glowB: 'lesson-lc-glow-b',
      keySectionTitle: 'Conceptos Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Semántica y Etimología',
        duration: '7-8 horas',
        lessons: 22,
        difficulty: 'medio',
        topics: [
          {
            name: 'Significado de Palabras',
            description: 'Estudio profundo del significado léxico, contextual y sus variaciones.',
            subtopics: [
              'Denotación y connotación',
              'Significado literal vs figurado',
              'Palabras polisémicas',
              'Campos semánticos',
              'Palabras polivalentes',
              'Significado y contexto',
              'Variaciones de significado por registro',
              'Significado etimológico vs actual',
              'Cambios de significado en el tiempo',
              'Significados regionales',
            ],
            examples: [
              'Denotación: gato = animal felino domesticado, cuadrúpedo',
              'Connotación: gato = fuerza, elegancia, independencia, astucia',
              'Polisemia: banco (mueble para sentarse vs institución financiera vs corriente marina)',
              'Literal: "Me hierven la sangre" = sangre caliente',
              'Figurado: "Me hierven la sangre" = estoy muy enfadado',
              'Campo semántico FAMILIA: padre, madre, hermano, tío, primo',
              'Campo semántico COLORES: rojo, azul, verde, amarillo, naranja',
              'Campo semántico EMOCIONES: alegría, tristeza, miedo, rabia, esperanza',
              'Polivalencia: "correr" (movimiento rápido, participar en carrera, fluir como agua)',
              'Registro formal: "fallecimiento" vs Registro coloquial: "muerte"',
            ],
          },
          {
            name: 'Origen y Etimología de Palabras',
            description: 'Rastreo de la etimología e historia de palabras, influencias lingüísticas.',
            subtopics: [
              'Etimología latina y griega',
              'Palabras de origen árabe en español',
              'Palabras de origen germánico',
              'Palabras de origen indígena (americanas)',
              'Cambios fonéticos en el tiempo',
              'Influencias de otras lenguas',
              'Palabras cognadas',
              'Etimología falsa o popular',
              'Neologismos y palabras nuevas',
              'Arcaísmos y palabras obsoletas',
            ],
            examples: [
              'Padre (latín: pater → español: padre)',
              'Filosofía (griego: philos=amor + sophia=sabiduría)',
              'Influencia árabe: almohada, aceite, alfombra, alcohol, álgebra',
              'Cognadas: padre (español) - padre (italiano) - père (francés) - pater (latín)',
              'Germánico: guerra (germánico WERRA), guardia (germánico WARDA)',
              'Indígena: tomate, chocolate, cacao, jaguar',
              'Cambio fonético: latín CANEM → español PERRO (cambio irregular)',
              'Etimología falsa: "máscara" no viene de "más cara"',
              'Neologismo: "computadora, internet, teléfono móvil"',
              'Arcaísmo: "agora" (ahora antiguo), "vos" (tú arcaico en algunas regiones)',
            ],
          },
          {
            name: 'Sinónimos y Antónimos',
            description: 'Relaciones entre palabras con significados similares, opuestos o complementarios.',
            subtopics: [
              'Sinónimos totales',
              'Sinónimos parciales (cuasi-sinónimos)',
              'Antónimos absolutos',
              'Antónimos relativos',
              'Niveles de registro lingüístico',
              'Precisión léxica',
              'Sinónimos por contexto',
              'Matices de significado',
              'Sinonimia figurada',
              'Antonimia parcial',
            ],
            examples: [
              'Sinónimos: hermoso ≈ bonito ≈ lindo (pero con matices)',
              'Cuasi-sinónimos: comenzar, empezar, iniciar (ligeramente diferentes)',
              'Antónimos absolutos: blanco ↔ negro, frío ↔ caliente',
              'Antónimos relativos: grande ↔ pequeño (depende del contexto)',
              'Sinónimo coloquial: "coche" vs formal: "automóvil"',
              'Precisión: "joven" (impreciso) vs "adolescente, muchacho, chaval" (preciso)',
              'Matiz: "delgado" (positivo) vs "flaco" (negativo) vs "esbelto" (muy positivo)',
              'Riqueza léxica: "triste" (genérico) vs "melancólico, apesadumbrado, desconsolado"',
              'Sinonimia figurada: "muerte" ≈ "eterno descanso"',
              'Antonimia parcial: "largo" se opone a "corto" pero existen "mediano, regular"',
            ],
          },
          {
            name: 'Relaciones Semánticas Complejas',
            description: 'Análisis de relaciones sutiles entre significados de palabras.',
            subtopics: [
              'Hiperónimos e hipónimos',
              'Holónimos y merónimos',
              'Palabras relacionadas por asociación',
              'Homónimos, homógrafos, homófonos',
              'Parónimos',
              'Palabras con raíz común',
              'Familias léxicas',
              'Fraseología y expresiones fijas',
              'Modismos regionais',
              'Equivalencias culturales',
            ],
            examples: [
              'Hiperónimo: "animal" (general) → Hipónimo: "perro" (específico)',
              'Holónimo: "árbol" (todo) → Merónimo: "rama, tronco, hoja" (partes)',
              'Homonimia: "banco" (mueble vs institución) - homógrafo (ortografía igual)',
              'Homófono: "ciento" vs "ciento" (pronunciación igual, diferente escritura)',
              'Parónimo: "afección" vs "infección" (escritura similar, significado diferente)',
              'Familia léxica: "libro, librería, libreta, librero, libretista"',
              'Fraseología: "al fin y al cabo", "en resumidas cuentas"',
              'Modismo: "estar en la luna", "tener pájaros en la cabeza"',
              'Equivalencia cultural: "siesta" en español ≈ "nap" en inglés',
              'Asociación: "fuego" → calor, llama, peligro, pasión',
            ],
          },
          {
            name: 'Análisis Semántico Aplicado',
            description: 'Aplicación práctica del análisis semántico en textos y comunicación.',
            subtopics: [
              'Análisis de campos semánticos en textos',
              'Coherencia semántica',
              'Coherencia textual',
              'Ambigüedad semántica',
              'Resolución de ambigüedad',
              'Elipsis semántica',
              'Ironía semántica',
              'Doble sentido',
              'Juegos de palabras',
              'Publicidad y manipulación semántica',
            ],
            examples: [
              'Campo semántico en texto: análisis de sinónimos usados',
              'Coherencia: todas las palabras contribuyen a significado unificado',
              'Ambigüedad: "Vi al hombre con el telescopio" (¿quién tiene el telescopio?)',
              'Resolución: "Vi al hombre (que tenía) el telescopio"',
              'Elipsis: "María es inteligente y (Juan es) trabajador"',
              'Ironía: "¡Qué inteligente!" (dice alguien tonto) = crítica implícita',
              'Doble sentido: "¿Quieres que te dé mi número?" (teléfono vs atención)',
              'Juego de palabras: "Soy un abogado (abogado por algo) y un abogado (profesional)"',
              'Publicidad: "Nuestro producto es lo más" (implicación de excelencia)',
            ],
          },
        ],
        keyFormulas: [
          'Denotación = significado literal y objetivo, diccionario',
          'Connotación = significado subjetivo, emocional, contextual',
          'Etimología = origen e historia de la palabra',
          'Sinónimo = palabras con significado similar (pero no idéntico)',
          'Antónimo = palabras con significado opuesto',
          'Campo semántico = conjunto de palabras con significados relacionados',
          'Hiperónimo = término general que incluye otros términos (animal > perro)',
          'Hipónimo = término específico incluido en uno general (perro < animal)',
        ],
        practiceExercises: [
          'Encontrar sinónimos precisos para palabras en contexto',
          'Identificar matices de significado entre sinónimos',
          'Clasificar palabras en campos semánticos',
          'Identificar denotación vs connotación en textos',
          'Rastrear etimología de palabras comunes',
          'Resolver crucigramas semánticos',
          'Analizar campos semánticos en prosas literarias',
          'Identificar y resolver ambigüedades semánticas',
          'Crear mapas mentales de familias léxicas',
          'Analizar homónimos y parónimos en textos',
          'Estudiar cambios semánticos en palabras',
          'Interpretar dobles sentidos y juegos de palabras',
        ],
      },
    },
  },
  ciencias: {
    biologia: {
      glowA: 'lesson-sci-glow-a',
      glowB: 'lesson-sci-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Biología Celular y Molecular Avanzada',
        duration: '8-9 horas',
        lessons: 26,
        difficulty: 'medio',
        topics: [
          {
            name: 'Célula',
            description: 'Estructura y función de la célula como unidad básica de la vida.',
            subtopics: [
              'Membrana celular y transporte',
              'Citoplasma y organelos',
              'Núcleo y material genético',
              'Diferencias procariota-eucariota',
            ],
            examples: [
              'Membrana: controla entrada/salida',
              'Mitocondria: producción de energía',
              'Núcleo: contiene ADN',
            ],
          },
          {
            name: 'ADN',
            description: 'Estructura molecular del ADN y su rol en la herencia.',
            subtopics: [
              'Estructura de doble hélice',
              'Bases nitrogenadas: A, T, G, C',
              'Replicación del ADN',
              'Código genético',
            ],
            examples: ['A se aparea con T', 'G se aparea con C', 'Replicación semiconservadora'],
          },
          {
            name: 'Mitosis',
            description: 'Proceso de división celular para crecimiento y reparación.',
            subtopics: [
              'Profase, metafase, anafase, telofase',
              'Huso mitótico',
              'Citocinesis',
              'Regulación del ciclo celular',
            ],
            examples: [
              'Cromosomas se alinean en metafase',
              'Separación de cromátidas en anafase',
              'Dos células hijas idénticas',
            ],
          },
        ],
        keyFormulas: [
          'Célula = unidad básica de vida',
          'ADN = ácido desoxirribonucleico',
          'Mitosis = 1 célula → 2 células idénticas',
          'Fotosíntesis: 6CO₂ + 6H₂O + luz → C₆H₁₂O₆ + 6O₂',
        ],
        practiceExercises: [
          'Etiquetar partes de célula animal vs vegetal',
          'Explicar replicación del ADN',
          'Ordenar fases de mitosis',
          'Comparar fotosíntesis y respiración',
        ],
      },
    },
    fisica: {
      glowA: 'lesson-sci-glow-a',
      glowB: 'lesson-sci-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Física Mecánica y Dinámica Avanzada',
        duration: '9-10 horas',
        lessons: 26,
        difficulty: 'medio-alto',
        topics: [
          {
            name: 'Fuerzas',
            description: 'Estudio de fuerzas, leyes de Newton y tipos de movimiento.',
            subtopics: [
              'Primera ley de Newton',
              'Segunda ley (F = ma)',
              'Tercera ley (acción-reacción)',
              'Fricción y fuerzas de contacto',
            ],
            examples: ['F = ma → a = F/m', 'Fricción opone el movimiento', 'Acción-reacción: pares de fuerzas'],
          },
          {
            name: 'Movimiento',
            description: 'Cinemática y descripción del movimiento de objetos.',
            subtopics: [
              'Desplazamiento, velocidad y aceleración',
              'Movimiento uniforme y variado',
              'Caída libre',
              'Movimiento circular',
            ],
            examples: ['v = d/t (velocidad)', 'a = Δv/Δt (aceleración)', 'h = gt²/2 (caída libre)'],
          },
          {
            name: 'Energía y Trabajo',
            description: 'Conceptos de energía cinética, potencial y conservación.',
            subtopics: ['Trabajo mecánico', 'Energía cinética y potencial', 'Conservación de energía', 'Potencia'],
            examples: ['W = F·d (trabajo)', 'Ec = ½mv² (energía cinética)', 'Ep = mgh (energía potencial)'],
          },
        ],
        keyFormulas: ['F = ma', 'v = v₀ + at', 'W = F·d', 'Ec = ½mv²', 'Ep = mgh', 'E_total = Ec + Ep'],
        practiceExercises: [
          'Calcular aceleración con F = 50N y m = 10kg',
          'Hallar velocidad final: v₀=5m/s, a=2m/s², t=3s',
          'Calcular trabajo con F=100N y d=5m',
          'Encontrar energía cinética de objeto m=2kg, v=10m/s',
        ],
      },
    },
    quimica: {
      glowA: 'lesson-sci-glow-a',
      glowB: 'lesson-sci-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Química Orgánica e Inorgánica Avanzada',
        duration: '10-11 horas',
        lessons: 28,
        difficulty: 'muy difícil',
        topics: [
          {
            name: 'Moléculas',
            description: 'Estructura de moléculas orgánicas con átomos de carbono.',
            subtopics: ['Enlaces covalentes', 'Cadenas de carbono', 'Grupos funcionales', 'Isómeros'],
            examples: ['Alcanos: C-C enlaces simples', 'Alquenos: C=C doble enlace', 'Benceno: anillo aromático'],
          },
          {
            name: 'Reacciones Orgánicas',
            description: 'Tipos de reacciones químicas en moléculas orgánicas.',
            subtopics: ['Sustitución y eliminación', 'Adición', 'Oxidación-reducción', 'Reacciones de condensación'],
            examples: [
              'Sustitución: R-X + Y⁻ → R-Y + X⁻',
              'Adición a doble enlace',
              'Combustión: CₙHₘ + O₂ → CO₂ + H₂O',
            ],
          },
          {
            name: 'Ácidos y Bases',
            description: 'Teoría de ácidos-bases de Brønsted-Lowry y pH.',
            subtopics: [
              'Definición ácido-base',
              'pH y pOH',
              'Reacciones de neutralización',
              'Buffer y soluciones amortiguadoras',
            ],
            examples: ['HCl es ácido fuerte', 'NaOH es base fuerte', 'pH = 7: neutro, <7: ácido, >7: básico'],
          },
        ],
        keyFormulas: [
          'pH = -log[H⁺]',
          'pOH = -log[OH⁻]',
          'pH + pOH = 14',
          '[H⁺][OH⁻] = 10⁻¹⁴',
          'Neutralización: ácido + base → sal + agua',
        ],
        practiceExercises: [
          'Calcular pH de solución con [H⁺] = 10⁻³',
          'Equilibrar ecuación: C₆H₁₂ + O₂ → CO₂ + H₂O',
          'Identificar grupo funcional en moléculas',
          'Escribir reacción de neutralización',
        ],
      },
    },
    ecologia: {
      glowA: 'lesson-sci-glow-a',
      glowB: 'lesson-sci-glow-b',
      keySectionTitle: 'Conceptos Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Ecología y Biodiversidad',
        duration: '7-8 horas',
        lessons: 22,
        difficulty: 'medio',
        topics: [
          {
            name: 'Ecosistemas',
            description: 'Estructura y funcionamiento de ecosistemas naturales.',
            subtopics: [
              'Componentes bióticos y abióticos',
              'Factores limitantes',
              'Biomas terrestres y acuáticos',
              'Sucesión ecológica',
            ],
            examples: [
              'Bióticos: plantas, animales, microorganismos',
              'Abióticos: luz, temperatura, agua, suelo',
              'Sabana, bosque tropical, océano',
            ],
          },
          {
            name: 'Cadenas Alimenticias',
            description: 'Flujo de energía y materia en los ecosistemas.',
            subtopics: [
              'Productores, consumidores, descomponedores',
              'Niveles tróficos',
              'Pirámides energéticas',
              'Redes tróficas',
            ],
            examples: [
              'Plantas → Herbívoros → Carnívoros',
              'Transferencia de energía: 10% por nivel',
              'Eficiencia energética',
            ],
          },
          {
            name: 'Ciclos Biogeoquímicos',
            description: 'Circulación de elementos en la naturaleza.',
            subtopics: ['Ciclo del carbono', 'Ciclo del nitrógeno', 'Ciclo del agua', 'Ciclo del fósforo'],
            examples: [
              'Ciclo C: fotosíntesis → respiración → combustión',
              'Ciclo N: N₂ → nitratos → proteínas',
              'Ciclo H₂O: evaporación → condensación → precipitación',
            ],
          },
        ],
        keyFormulas: [
          'Energía bruta = calorías consumidas',
          'Energía neta = energía bruta - energía de respiration',
          'Eficiencia de transferencia ≈ 10%',
          'Nutrientes circulan en ciclos cerrados',
        ],
        practiceExercises: [
          'Dibujar una cadena alimenticia con 4 niveles',
          'Calcular energía disponible en cada nivel trófico',
          'Explicar ciclo del carbono',
          'Identificar factores limitantes en un bioma',
        ],
      },
    },
    termodinamica: {
      glowA: 'lesson-sci-glow-a',
      glowB: 'lesson-sci-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Termodinámica y Termoquímica Avanzada',
        duration: '8-9 horas',
        lessons: 24,
        difficulty: 'muy difícil',
        topics: [
          {
            name: 'Calor y Temperatura',
            description: 'Conceptos fundamentales de temperatura, calor y equilibrio térmico.',
            subtopics: [
              'Temperatura y energía cinética',
              'Transferencia de calor',
              'Modos de transferencia: conducción, convección, radiación',
              'Dilatación térmica',
            ],
            examples: ['T(K) = T(°C) + 273', 'Q = m·c·ΔT', 'Conducción en metales, convección en fluidos'],
          },
          {
            name: 'Leyes de la Termodinámica',
            description: 'Principios fundamentales que rigen los procesos termodinámicos.',
            subtopics: [
              'Primera ley: conservación de energía',
              'Segunda ley: entropía',
              'Tercera ley: cero absoluto',
              'Máquinas térmicas',
            ],
            examples: ['ΔU = Q - W (primera ley)', 'ΔS ≥ 0 (segunda ley)', 'Eficiencia: η = W/Q_entrada'],
          },
          {
            name: 'Entropía',
            description: 'Concepto de desorden y dirección de procesos naturales.',
            subtopics: [
              'Definición de entropía',
              'Orden y desorden molecular',
              'Espontaneidad de procesos',
              'Relación con energía libre de Gibbs',
            ],
            examples: [
              'Entropía aumenta en sistemas aislados',
              'Gas se expande espontáneamente',
              'Cristales se disuelven en agua',
            ],
          },
        ],
        keyFormulas: [
          'Q = m·c·ΔT (calor)',
          'ΔU = Q - W (primera ley)',
          'W = P·ΔV (trabajo)',
          'η = 1 - Q_fría/Q_caliente (eficiencia)',
          'ΔG = ΔH - T·ΔS',
        ],
        practiceExercises: [
          'Calcular calor necesario para elevar T de agua',
          'Aplicar primera ley a sistema de gas',
          'Calcular trabajo realizado en expansión',
          'Determinar espontaneidad de reacción',
        ],
      },
    },
  },
  sociales: {
    historia: {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-math-glow-b',
      keySectionTitle: 'Hitos Importantes',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Historia de Colombia',
        duration: '7-8 horas',
        lessons: 20,
        difficulty: 'fácil',
        topics: [
          {
            name: 'Periodo Precolombino',
            description: 'Historia de civilizaciones indígenas antes de la conquista española.',
            subtopics: [
              'Pueblos indígenas: Muiscas, Taironas, Quimbayas',
              'Organización social y política',
              'Avances tecnológicos y artísticos',
              'Sistemas de gobierno',
            ],
            examples: [
              'Muiscas: confederación de cacicazgos',
              'Cultura Tayrona: ciudades en la sierra',
              'Cerámica y orfebrería avanzada',
            ],
          },
          {
            name: 'Época Colonial',
            description: 'Dominio español y cambios socioculturales en el territorio.',
            subtopics: [
              'Conquista y colonización',
              'Encomienda y sistemas de trabajo',
              'Mestizaje y mezcla cultural',
              'Estructuras coloniales',
            ],
            examples: ['Llegada de Colón en 1492', 'Fundación de Cartagena y Bogotá', 'Virreinato de Nueva Granada'],
          },
          {
            name: 'República',
            description: 'Independencia y formación del estado colombiano moderno.',
            subtopics: [
              'Movimientos independentistas',
              'Proceso de emancipación',
              'Constituciones y reformas políticas',
              'Conflictos internos y bipartidismo',
            ],
            examples: ['Grito de Independencia: 20 de julio', 'Constitución de 1886', 'Frente Nacional (1958-1974)'],
          },
        ],
        keyFormulas: [
          '1492: Llegada de Colón',
          '1810: Grito de Independencia',
          '1819: Batalla de Boyacá',
          '1886: Constitución Política',
        ],
        practiceExercises: [
          'Identificar principales pueblos indígenas',
          'Explicar sistema de encomienda',
          'Enumerar próceres de la independencia',
          'Analizar período colonial vs república',
        ],
      },
    },
    geografia: {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-math-glow-b',
      keySectionTitle: 'Datos Importantes',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Geografía Política',
        duration: '6-7 horas',
        lessons: 18,
        difficulty: 'fácil',
        topics: [
          {
            name: 'División Política',
            description: 'Organización territorial y divisiones administrativas mundiales.',
            subtopics: ['Continentes y océanos', 'Países y fronteras', 'Regiones administrativas', 'Geopolítica'],
            examples: [
              '6 continentes: África, América, Asia, Europa, Oceanía, Antártida',
              '195 países reconocidos en el mundo',
              'Colombia: 32 departamentos + Bogotá',
            ],
          },
          {
            name: 'Geografía de Colombia',
            description: 'Características geográficas y territoriales de Colombia.',
            subtopics: [
              'Regiones naturales: Caribe, Pacífica, Andina, Orinoquía, Amazonía',
              'Cordilleras andinas',
              'Costas atlántica y pacífica',
              'Recursos naturales y biodiversidad',
            ],
            examples: ['1.3 millones km² de territorio', 'Segunda mayor biodiversidad mundial', 'Capital: Bogotá D.C.'],
          },
          {
            name: 'Recursos Naturales',
            description: 'Distribución y aprovechamiento de recursos en el planeta.',
            subtopics: [
              'Recursos renovables y no renovables',
              'Petróleo, minerales, agua',
              'Bosques y flora',
              'Fauna y ecosistemas',
            ],
            examples: [
              'Petróleo: recurso no renovable',
              'Agua: recurso renovable esencial',
              'Bosques tropicales: biodiversidad',
            ],
          },
        ],
        keyFormulas: [
          'Área total Colombia: 1.141.748 km²',
          'Población: ~50 millones',
          '32 departamentos + capital',
          'Posición: 4°-5° biodiversidad mundial',
        ],
        practiceExercises: [
          'Localizar continentes y océanos en mapa',
          'Identificar las 5 regiones naturales',
          'Enumerar departamentos colombianos',
          'Analizar distribución de recursos',
        ],
      },
    },
    economia: {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-math-glow-b',
      keySectionTitle: 'Conceptos Fundamentales',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Economía',
        duration: '7-8 horas',
        lessons: 19,
        difficulty: 'medio',
        topics: [
          {
            name: 'Sistemas Económicos',
            description: 'Clasificación y características de los principales sistemas económicos.',
            subtopics: [
              'Capitalismo y libre mercado',
              'Socialismo y economía planificada',
              'Economía mixta',
              'Modelos económicos actuales',
            ],
            examples: [
              'EE.UU.: economía capitalista',
              'Mercados: determinan precios',
              'Estado: regula en economía mixta',
            ],
          },
          {
            name: 'Oferta y Demanda',
            description: 'Mecanismos fundamentales del mercado y formación de precios.',
            subtopics: ['Ley de oferta y demanda', 'Equilibrio de mercado', 'Elasticidad', 'Desplazamientos de curvas'],
            examples: ['Demanda ↑ → Precio ↑', 'Oferta ↑ → Precio ↓', 'Equilibrio: cantidad demandada = ofrecida'],
          },
          {
            name: 'Indicadores Económicos',
            description: 'Medidas clave para evaluar la salud de una economía.',
            subtopics: ['PIB (Producto Interno Bruto)', 'Inflación y deflación', 'Desempleo', 'Balanza comercial'],
            examples: [
              'PIB Colombia 2023: ~$315 mil millones',
              'Inflación: aumento general de precios',
              'Desempleo: porcentaje sin trabajo',
            ],
          },
        ],
        keyFormulas: [
          'Demanda: D = f(Precio)',
          'Oferta: S = f(Precio)',
          'Equilibrio: Qd = Qs',
          'Inflación = (IPC_actual - IPC_anterior) / IPC_anterior × 100',
        ],
        practiceExercises: [
          'Graficar curvas de oferta y demanda',
          'Calcular cambios de precio por exceso/escasez',
          'Analizar efecto de inflación',
          'Comparar sistemas económicos',
        ],
      },
    },
    ciudadania: {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-math-glow-b',
      keySectionTitle: 'Pilares Fundamentales',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Competencias Ciudadanas',
        duration: '5-6 horas',
        lessons: 14,
        difficulty: 'fácil',
        topics: [
          {
            name: 'Derechos y Deberes',
            description: 'Derechos humanos fundamentales y responsabilidades ciudadanas.',
            subtopics: [
              'Derechos civiles y políticos',
              'Derechos económicos y sociales',
              'Deberes ciudadanos',
              'Protección de derechos',
            ],
            examples: [
              'Derecho a la vida, libertad, igualdad',
              'Deber de respetar derechos ajenos',
              'Participación democrática',
            ],
          },
          {
            name: 'Sistemas Democráticos',
            description: 'Principios y funcionamiento de democracias en el mundo.',
            subtopics: [
              'Democracia directa e indirecta',
              'Separación de poderes',
              'Elecciones y voto',
              'Instituciones democráticas',
            ],
            examples: ['Poder ejecutivo, legislativo, judicial', 'Sufragio universal', 'Congreso y asambleas'],
          },
          {
            name: 'Convivencia Social',
            description: 'Bases para una sociedad pacífica y tolerante.',
            subtopics: [
              'Respeto a la diferencia',
              'Resolución de conflictos',
              'Inclusión y equidad',
              'Construcción de paz',
            ],
            examples: ['Diálogo y empatía', 'Mediación en conflictos', 'Justicia transicional'],
          },
        ],
        keyFormulas: [
          'Derechos + Deberes = Ciudadanía',
          'Democracia = Poder del pueblo',
          'Paz = Respeto mutuo',
          'Inclusión = Igualdad de oportunidades',
        ],
        practiceExercises: [
          'Enumerar derechos fundamentales',
          'Explicar separación de poderes',
          'Proponer soluciones a conflictos',
          'Analizar casos de discriminación',
        ],
      },
    },
    filosofia: {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-math-glow-b',
      keySectionTitle: 'Definiciones Clave',
      practiceSectionTitle: 'Ejercicios de Práctica',
      content: {
        title: 'Filosofía y Ética',
        duration: '8-9 horas',
        lessons: 21,
        difficulty: 'difícil',
        topics: [
          {
            name: 'Teorías Éticas',
            description: 'Principales teorías sobre la moral y lo correcto.',
            subtopics: [
              'Deontología: deber y normas',
              'Consecuencialismo: utilitarismo',
              'Ética de virtudes',
              'Ética contemporánea',
            ],
            examples: [
              'Kant: deber como fundamento',
              'Utilitarismo: máxima felicidad',
              'Aristóteles: virtudes y hábitos',
            ],
          },
          {
            name: 'Metafísica',
            description: 'Preguntas fundamentales sobre la realidad y el ser.',
            subtopics: [
              '¿Qué es la realidad?',
              'Sustancia y propiedades',
              'Causa y efecto',
              'Liberta versus determinismo',
            ],
            examples: [
              'Realismo: mundo existe independiente',
              'Idealismo: realidad depende de mente',
              'Causalidad: relación causa-efecto',
            ],
          },
          {
            name: 'Epistemología',
            description: 'Estudio del conocimiento y cómo sabemos lo que sabemos.',
            subtopics: [
              'Fundamentos del conocimiento',
              'Verdad y justificación',
              'Escepticismo y relativismo',
              'Método científico',
            ],
            examples: [
              'Empirismo: conocimiento por experiencia',
              'Racionalismo: conocimiento por razón',
              'Ciencia: método empírico-deductivo',
            ],
          },
        ],
        keyFormulas: [
          'Ética = Ciencia de la moral',
          'Virtud = Hábito de obrar bien',
          'Conocimiento = Creencia verdadera justificada',
          'Realidad = Lo que existe independientemente',
        ],
        practiceExercises: [
          'Analizar dilema ético desde diferentes teorías',
          'Debatir sobre libertad versus determinismo',
          'Comparar empirismo vs racionalismo',
          'Evaluar criterios de verdad',
        ],
      },
    },
  },
  ingles: {
    gramatica: {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-eng-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Práctica sugerida',
      content: {
        title: 'Gramática en inglés',
        duration: '2-3 horas',
        lessons: 6,
        difficulty: 'básico',
        topics: [
          {
            name: 'Presente simple y continuo',
            description: 'Cuándo usar "I work" frente a "I am working".',
            subtopics: [
              'Present simple (habits, facts)',
              'Present continuous (now, temporary)',
              'Adverbs of frequency',
            ],
            examples: ['I study every day.', 'She is reading now.', 'They usually walk to school.'],
          },
          {
            name: 'Artículos y sustantivos',
            description: 'Uso de a/an/the y plurales irregulares.',
            subtopics: ['A/an con sonido consonante/vocal', 'The para específico', 'Plurales: child→children'],
            examples: ['an hour', 'a university', 'the book on the table', 'two men'],
          },
        ],
        keyFormulas: [
          'S + V(s/es) + O → He plays tennis.',
          'S + am/is/are + V-ing → They are studying.',
          'There is / There are → There is a pen; there are two pens.',
        ],
        practiceExercises: [
          'Elegir entre present simple y continuous en 5 oraciones.',
          'Completar con a/an/the o dejar en blanco si no hace falta.',
        ],
      },
    },
    vocabulario: {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-eng-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Práctica sugerida',
      content: {
        title: 'Vocabulario esencial',
        duration: '2 horas',
        lessons: 5,
        difficulty: 'básico',
        topics: [
          {
            name: 'Cognados y falsos amigos',
            description: 'Palabras que se parecen al español y trampas comunes.',
            subtopics: ['Cognados: important, family, university', 'Falsos amigos: actually ≠ actualmente'],
            examples: [
              '"Actually" = en realidad, no "actualmente" (currently).',
              '"Sensitive" ≠ sensible (reasonable).',
            ],
          },
          {
            name: 'Campos temáticos ICFES',
            description: 'Grupos de palabras frecuentes en textos del examen.',
            subtopics: ['Educación: assignment, deadline, scholarship', 'Medio ambiente: pollution, renewable'],
            examples: ['submit an assignment', 'renewable energy sources'],
          },
        ],
        keyFormulas: [
          'Prefijos: un- (unhappy), re- (rewrite), dis- (disagree)',
          'Sufijos: -tion (information), -ment (development), -ness (happiness)',
        ],
        practiceExercises: [
          'Clasificar 10 palabras en cognado vs falso amigo.',
          'Completar un párrafo sobre escuela con el vocabulario dado.',
        ],
      },
    },
    lectura: {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-eng-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Práctica sugerida',
      content: {
        title: 'Comprensión de lectura',
        duration: '2 horas',
        lessons: 4,
        difficulty: 'básico',
        topics: [
          {
            name: 'Idea principal y detalles',
            description: 'Localizar el mensaje central y datos explícitos en el texto.',
            subtopics: ['Topic sentence al inicio o al final del párrafo', 'Scanning para fechas y nombres'],
            examples: ['Pregunta típica: What is the passage mainly about?', 'According to the text, ...'],
          },
          {
            name: 'Inferencia y vocabulario en contexto',
            description: 'Deducir significado cuando la palabra es nueva.',
            subtopics: ['Pistas antes y después de la palabra desconocida', 'Tono: positive/negative/neutral'],
            examples: ['The author implies that...', 'In line 3, "arduous" is closest in meaning to difficult.'],
          },
        ],
        keyFormulas: [
          'Main idea ≠ first sentence siempre; resume lo que se repite.',
          'Para "refer to", sustituye el pronombre por el sustantivo del párrafo anterior.',
        ],
        practiceExercises: [
          'Leer un corto texto y elegir el título más adecuado.',
          'Responder 3 preguntas de detalle y 1 de inferencia.',
        ],
      },
    },
    'tiempos-verbales': {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-eng-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Práctica sugerida',
      content: {
        title: 'Tiempos verbales clave',
        duration: '2-3 horas',
        lessons: 5,
        difficulty: 'intermedio',
        topics: [
          {
            name: 'Pasado: simple vs continuo vs present perfect',
            description: 'Elegir el tiempo según el enlace temporal del enunciado.',
            subtopics: [
              'Past simple: acción terminada (yesterday, in 2010)',
              'Past continuous: interrupción (was studying when...)',
              'Present perfect: experiencia o resultado con vínculo al presente (ever, since, yet)',
            ],
            examples: ['I finished at 5 pm.', 'I was reading at 8 pm.', 'I have visited London twice.'],
          },
          {
            name: 'Futuro: will, going to, present continuous',
            description: 'Planes firmes vs predicciones espontáneas.',
            subtopics: [
              'Going to: intención previa',
              'Will: decisión en el momento',
              'Present continuous: arreglo fijado',
            ],
            examples: ['I think it will rain.', 'I am going to study medicine.', 'I am meeting her at 6.'],
          },
        ],
        keyFormulas: [
          'By the time + past perfect → By the time I arrived, the film had started.',
          'Since + present perfect → I have lived here since 2020.',
        ],
        practiceExercises: [
          'Elegir entre past simple y present perfect en un párrafo.',
          'Completar con will o going to según el contexto.',
        ],
      },
    },
    conectores: {
      glowA: 'lesson-math-glow-a',
      glowB: 'lesson-eng-glow-b',
      keySectionTitle: 'Fórmulas Clave',
      practiceSectionTitle: 'Práctica sugerida',
      content: {
        title: 'Conectores y cohesión',
        duration: '1-2 horas',
        lessons: 4,
        difficulty: 'básico',
        topics: [
          {
            name: 'Adición y contraste',
            description: 'Unir ideas con claridad en el ensayo o la respuesta abierta.',
            subtopics: ['Adición: moreover, furthermore, in addition', 'Contraste: however, although, whereas'],
            examples: ['The plan is cheap; moreover, it is fast.', 'Although it was late, we continued.'],
          },
          {
            name: 'Causa y consecuencia',
            description: 'Relaciones lógicas muy frecuentes en preguntas tipo cloze.',
            subtopics: ['Causa: because, since, due to', 'Consecuencia: therefore, as a result, so'],
            examples: ['Since traffic was heavy, we were late.', 'He studied hard; therefore, he passed.'],
          },
        ],
        keyFormulas: [
          'Although + oración, NO repitas but en la misma oración.',
          'Due to + sustantivo / Due to the fact that + oración',
        ],
        practiceExercises: [
          'Unir dos oraciones cortas usando however y because correctamente.',
          'Completar un texto con 5 conectores del listado.',
        ],
      },
    },
  },
};
